---
- name: Create CMOS Exporter Service
  template:
    src: cmos-exporter.service.j2
    dest: "{{ _cmos_exporter_systemd_path }}/{{ _cmos_exporter_systemd_unit }}"
    owner: root
    group: root
    mode: 0755

- name: Create CMOS Exporter Config
  template:
    src: config.yml.j2
    dest: "{{ cmos_exporter_conf_dir }}/{{ cmos_exporter_conf_file }}"
    owner: root
    group: "{{ cmos_exporter_user_group }}"
    mode: 0640
