---
- name: Add user group "{{ cmos_exporter_user_group }}"
  group:
    name: "{{ cmos_exporter_user }}"
    system: true
    state: present

- name: Add user "cmos-exporter"
  user:
    name: "{{ cmos_exporter_user }}"
    comment: "CMOS Account"
    groups:
      - "{{ cmos_exporter_user_group }}"
    system: true
    shell: "/usr/sbin/nologin"
    createhome: false

- name: Install Directory
  block:
    - name: Create CMOS Install Directory
      file:
        path: "{{ cmos_exporter_install_dir }}"
        state: directory
        owner: root
        group: "{{ cmos_exporter_user_group }}"
        mode: 0770

    - name: Create CMOS Conf Directory
      file:
        path: "{{ cmos_exporter_conf_dir }}"
        state: directory
        owner: root
        group: "{{ cmos_exporter_user_group }}"
        mode: 0755

- name: Create Temp Directory
  block:
    - name: Remove CMOS Exporter temp Directory if it exists
      become: false
      file:
        path: "{{ cmos_exporter_local_tmp_dir }}"
        state: absent
      delegate_to: localhost
      check_mode: false

    - name: Create CMOS Exporter temp Directory
      become: false
      file:
        path: "{{ cmos_exporter_local_tmp_dir }}"
        state: directory
      delegate_to: localhost
      check_mode: false

- name: Download CMOS Exporter binary to local folder
  become: false
  get_url:
    url: "{{ cmos_exporter_download_url }}"
    dest: "{{ cmos_exporter_local_tmp_dir }}/cmos-exporter"
  register: _download_binary
  until: _download_binary is succeeded
  retries: 5
  delay: 2
  delegate_to: localhost
  check_mode: false

- name: Propagate CMOS Exporter binary
  copy:
    src: "{{ cmos_exporter_local_tmp_dir }}/cmos-exporter"
    dest: "{{ cmos_exporter_install_dir }}/{{ cmos_exporter_binary }}"
    mode: 0755
    owner: root
    group: "{{ cmos_exporter_user_group }}"

- name: Create CMOS Exporter Service
  template:
    src: cmos-exporter.service.j2
    dest: "{{ _cmos_exporter_systemd_path }}/{{ _cmos_exporter_systemd_unit }}"
    owner: root
    group: root
    mode: 0755
