---
- name: Add user group "{{ cmos_exporter_user_group }}"
  group:
    name: "{{ cmos_exporter_user_group }}"
    system: true
    state: present

- name: Add user "cmos-exporter"
  user:
    name: "{{ cmos_exporter_user }}"
    comment: "CMOS Account"
    groups:
      - "{{ cmos_exporter_user_group }}"
    system: true
    shell: "{{ cmos_exporter_user_shell }}"
    createhome: "{{ cmos_exporter_user_createhome }}"
  when: cmos_exporter_user != 'root'

- name: Install Directory
  block:
    - name: Create CMOS Install Directory
      file:
        path: "{{ cmos_exporter_install_dir }}"
        state: directory
        owner: root
        group: "{{ cmos_exporter_user_group }}"
        mode: 0770

    - name: Create CMOS Conf Directory
      file:
        path: "{{ cmos_exporter_conf_dir }}"
        state: directory
        owner: root
        group: "{{ cmos_exporter_user_group }}"
        mode: 0755

- name: Download CMOS Exporter Binary to controller
  block:
    - name: Create CMOS Exporter temp Directory
      become: false
      file:
        path: "{{ cmos_exporter_local_tmp_dir }}"
        state: directory
      delegate_to: localhost
      check_mode: false

    - name: Download CMOS Exporter binary to local folder
      become: false
      get_url:
        url: "{{ cmos_exporter_download_url }}"
        dest: "{{ cmos_exporter_local_tmp_dir }}/{{ cmos_exporter_binary }}"
      register: _download_binary
      until: _download_binary is succeeded
      retries: 5
      delay: 2
      delegate_to: localhost
      check_mode: false

    - name: Set local path
      ansible.builtin.set_fact:
        __cmos_exporter_local_binary_path: "{{ cmos_exporter_local_tmp_dir }}/{{ cmos_exporter_binary }}"

  when: (cmos_exporter_local_binary_path is not defined) or (cmos_exporter_local_binary_path | length == 0)

- name: Set local path
  ansible.builtin.set_fact:
    __cmos_exporter_local_binary_path: "{{ cmos_exporter_local_binary_path }}"
  when: cmos_exporter_local_binary_path is defined and cmos_exporter_local_binary_path | length > 0

- name: Propagate CMOS Exporter binary
  copy:
    src: "{{ __cmos_exporter_local_binary_path }}"
    dest: "{{ cmos_exporter_install_dir }}/{{ cmos_exporter_binary }}"
    mode: 0755
    owner: root
    group: "{{ cmos_exporter_user_group }}"
