---
- include: preflight.yml
  become: true
  tags:
    - cmos_exporter_install
    - cmos_exporter_configure
    - cmos_exporter_run

- include: install.yml
  become: true
  when: __cmos_exporter_do_install
  tags:
    - cmos_exporter_install

- include: configure.yml
  become: true
  tags:
    - cmos_exporter_configure

- name: Ensure CMOS Exporter is enabled on boot
  become: true
  systemd:
    daemon_reload: true
    name: cmos-exporter
    enabled: true
    state: started
  tags:
    - cmos_exporter_run
