name: Editor Config

on:
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: EditorConfig-Action
        uses: zbeekman/EditorConfig-Action@master
