name: Yaml Lint

on:
  - push
  - pull_request

jobs:
  lintAllTheThings:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: yaml-lint
        id: yaml-lint
        uses: ibiqlik/action-yamllint@v3
        with:
          file_or_dir: .
